
services:

  backend:
    container_name: backend
    image: swithserver/ubuntu:latest
    expose:
      - "8080:8080"
    networks:
      - swith

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
        - ./conf.d:/etc/nginx/conf.d
        - /etc/letsencrypt/live/swithweb.com:/etc/letsencrypt/live/swithweb.com:ro
        - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
    depends_on:
      - backend
    networks:
      - swith
    restart: always



  certbot:
     container_name: certbot
     image: certbot/certbot:latest
     volumes:
       - /etc/letsencrypt:/etc/letsencrypt

     entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew --quiet; done;'"
     networks:
       - swith



networks:
  swith:
