
services:

  backend:
    container_name: backend
    image: swithserver/ubuntu:latest
    environment:
      - TZ=Asia/Seoul
    expose:
      - "8080:8080"
    networks:
      - swith

  frontend:
    container_name: frontend
    image: swithserver/front
    environment:
      - TZ=Asia/Seoul
    expose:
      - "3000"
    networks:
      - swith

  nginx:
    container_name: nginx
    image: nginx:latest
    environment:
      - TZ=Asia/Seoul
    ports:
      - "80:80"
      - "443:443"
    volumes:
        - ./conf.d:/etc/nginx/conf.d
        - /etc/letsencrypt/live/swithweb.com:/etc/letsencrypt/live/swithweb.com:ro
        - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
        - /var/lib/GeoIP/GeoLite2-Country.mmdb:/var/lib/GeoIP/GeoLite2-Country.mmdb # GeoIP 마운트
    depends_on:
      - backend
      - frontend
    networks:
      - swith
    restart: always


  certbot:
     container_name: certbot
     image: certbot/certbot:latest
     environment:
       - TZ=Asia/Seoul
     volumes:
       - /etc/letsencrypt:/etc/letsencrypt

     entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew --quiet; done;'"
     networks:
       - swith



networks:
  swith:
